apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: tomcat-demo-deployment
spec:
  replicas: 2
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: tomcat-demo
    spec:
      containers:
        - name: tomcat-demo-pod
          image: hello:v2
          ports:
            - containerPort: 8080